# Generated by Django 4.0.2 on 2022-02-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=40, verbose_name='Логін')),
                ('password', models.CharField(max_length=40, verbose_name='Пароль')),
            ],
        ),
        migrations.CreateModel(
            name='Lviv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Дата і час')),
                ('T', models.IntegerField(verbose_name='Температура')),
                ('dd', models.CharField(max_length=25, verbose_name='Напрям вітру')),
                ('FF', models.IntegerField(verbose_name='Швидкість вітру')),
            ],
        ),
    ]
