# Generated by Django 4.0.2 on 2022-02-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_kyiv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dnipropetrovsk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Дата і час')),
                ('T', models.IntegerField(verbose_name='Температура')),
                ('dd', models.CharField(max_length=25, verbose_name='Напрям вітру')),
                ('FF', models.IntegerField(verbose_name='Швидкість вітру')),
            ],
        ),
        migrations.CreateModel(
            name='Donetsk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Дата і час')),
                ('T', models.IntegerField(verbose_name='Температура')),
                ('dd', models.CharField(max_length=25, verbose_name='Напрям вітру')),
                ('FF', models.IntegerField(verbose_name='Швидкість вітру')),
            ],
        ),
        migrations.CreateModel(
            name='Ivano_Frankivsk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Дата і час')),
                ('T', models.IntegerField(verbose_name='Температура')),
                ('dd', models.CharField(max_length=25, verbose_name='Напрям вітру')),
                ('FF', models.IntegerField(verbose_name='Швидкість вітру')),
            ],
        ),
        migrations.CreateModel(
            name='Kharkiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Дата і час')),
                ('T', models.IntegerField(verbose_name='Температура')),
                ('dd', models.CharField(max_length=25, verbose_name='Напрям вітру')),
                ('FF', models.IntegerField(verbose_name='Швидкість вітру')),
            ],
        ),
        migrations.CreateModel(
            name='Krivoy_rog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Дата і час')),
                ('T', models.IntegerField(verbose_name='Температура')),
                ('dd', models.CharField(max_length=25, verbose_name='Напрям вітру')),
                ('FF', models.IntegerField(verbose_name='Швидкість вітру')),
            ],
        ),
        migrations.CreateModel(
            name='Luhansk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Дата і час')),
                ('T', models.IntegerField(verbose_name='Температура')),
                ('dd', models.CharField(max_length=25, verbose_name='Напрям вітру')),
                ('FF', models.IntegerField(verbose_name='Швидкість вітру')),
            ],
        ),
        migrations.CreateModel(
            name='Odessa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Дата і час')),
                ('T', models.IntegerField(verbose_name='Температура')),
                ('dd', models.CharField(max_length=25, verbose_name='Напрям вітру')),
                ('FF', models.IntegerField(verbose_name='Швидкість вітру')),
            ],
        ),
    ]
