# Generated by Django 4.0.2 on 2022-02-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_dnipropetrovsk_donetsk_ivano_frankivsk_kharkiv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simferopol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Дата і час')),
                ('T', models.IntegerField(verbose_name='Температура')),
                ('dd', models.CharField(max_length=25, verbose_name='Напрям вітру')),
                ('FF', models.IntegerField(verbose_name='Швидкість вітру')),
            ],
        ),
    ]
